name: Coveralls

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go test -v -coverprofile=profile.cov ./...

      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.7.0
        with:
          path-to-profile: profile.cov
          flag-name: Go-1.19

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: goveralls -coverprofile=profile.cov -service=github
