name: GoVulnCheck

on:
  push:
  pull_request:

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action
        with:
          vulncheck-version: latest
          fail-on-vuln: true
          github-token: ${GH_TOKEN}
