name: Snyk

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  snyk:
    name: "Snyk Code Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${{secrets.SNYK_TOKEN}}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
