name: Vulnerabilities

on:
  push:
  pull_request:

permissions: read-all

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      - name: Scan for Vulnerabilities in Code
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
